-- cpq_product_model
  `model_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '????',
  `catalog_id` bigint NOT NULL COMMENT '????ID',
  `model_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????/??(L4)',
  `model_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '????',
  `lifecycle_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'ACTIVE' COMMENT '????: CONCEPT/DESIGN/PRE_RELEASE/ACTIVE/EOL_ANNOUNCED/LAST_TIME_BUY/DISCONTINUED/ARCHIVED',
  `successor_model_id` bigint DEFAULT NULL COMMENT '????ID(???)',
  `base_price` decimal(18,2) DEFAULT NULL COMMENT '?????',
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'CNY' COMMENT '??',
  `min_order_qty` int DEFAULT '1' COMMENT '?????',
  `lead_time_days` int DEFAULT NULL COMMENT '????(?)',
  `config_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'STANDARD' COMMENT '????: STANDARD/ATO/CTO/ETO/BUNDLE',
  `default_bom_id` bigint DEFAULT NULL COMMENT '??SBOM Header ID',
  `thumbnail_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '?????(OSS??)',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `category_id` bigint NOT NULL COMMENT '????ID(FK?cpq_product_category, ??L3????)',
  PRIMARY KEY (`model_id`),
  UNIQUE KEY `uk_model_code` (`tenant_id`,`model_code`),
  KEY `idx_catalog` (`tenant_id`,`catalog_id`),
  KEY `idx_lifecycle` (`tenant_id`,`lifecycle_status`),
  KEY `idx_product_line` (`tenant_id`),
  KEY `idx_search` (`tenant_id`,`model_name`,`model_code`),
  KEY `idx_category` (`tenant_id`,`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ?????'

-- cpq_product_attribute
  `attribute_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '????',
  `model_id` bigint NOT NULL COMMENT '????ID',
  `attr_category` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????(Feature Category)',
  `attr_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????(Feature)',
  `attr_value` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '?????(Option)',
  `is_configurable` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '?????(0? 1?)',
  `is_required` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0? 1?)',
  `display_order` int DEFAULT '0' COMMENT '????',
  `data_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'STRING' COMMENT '????: STRING/NUMBER/BOOLEAN/ENUM',
  `option_values` json DEFAULT NULL COMMENT '?????(JSON??, data_type=ENUM???)',
  `sort_order` int DEFAULT '0',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`attribute_id`),
  UNIQUE KEY `uk_model_attr` (`tenant_id`,`model_id`,`attr_name`),
  KEY `idx_model` (`tenant_id`,`model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????'

-- cpq_attribute_option
  `option_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `model_id` bigint NOT NULL COMMENT '??ID(FK?cpq_product_model)',
  `attr_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???',
  `option_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `option_label` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '?????',
  `option_value` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '???',
  `is_default` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??????',
  `sort_order` int DEFAULT '0' COMMENT '???',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`option_id`),
  UNIQUE KEY `uk_attr_option` (`tenant_id`,`model_id`,`attr_name`,`option_code`),
  KEY `idx_model_attr` (`tenant_id`,`model_id`,`attr_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ???????(????????)'

-- cpq_config_rule
  `rule_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `rule_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `rule_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: VALIDATION(??????)/SELECTION(??????)/ALERT(????)/VISIBILITY(?????)',
  `model_id` bigint DEFAULT NULL COMMENT '????ID(FK?cpq_product_model, ????????)',
  `condition_expr` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '?????(JSON/DSL, ?????????)',
  `action_expr` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '?????(JSON/DSL, ??????????)',
  `error_message` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??????????',
  `severity` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'ERROR' COMMENT '????: ERROR/WARNING/INFO',
  `priority` int DEFAULT '0' COMMENT '???(????)',
  `effective_date` date NOT NULL COMMENT '????',
  `expiry_date` date DEFAULT NULL COMMENT '????',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`rule_id`),
  KEY `idx_model` (`tenant_id`,`model_id`),
  KEY `idx_type` (`tenant_id`,`rule_type`),
  KEY `idx_active` (`tenant_id`,`status`,`effective_date`,`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(CSP????)'

-- cpq_attribute_mapping
  `mapping_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `model_id` bigint NOT NULL COMMENT '??ID(FK?cpq_product_model)',
  `attr_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???',
  `attr_value` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???',
  `material_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `sbom_line_id` bigint DEFAULT NULL COMMENT '??SBOM?ID(FK?cpq_sbom_line)',
  `condition_expr` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `sort_order` int DEFAULT '0' COMMENT '???',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`mapping_id`),
  UNIQUE KEY `uk_attr_value` (`tenant_id`,`model_id`,`attr_name`,`attr_value`),
  KEY `idx_model_attr` (`tenant_id`,`model_id`,`attr_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????????(???????????????????, SBOM?MBOM????)'

-- cpq_sbom_header
  `sbom_header_id` bigint NOT NULL COMMENT 'SBOM?ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '????',
  `model_id` bigint NOT NULL COMMENT '????ID',
  `sbom_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'SBOM??',
  `sbom_version` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1.0' COMMENT 'SBOM??',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`sbom_header_id`),
  KEY `idx_model` (`tenant_id`,`model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??BOM?'

-- cpq_sbom_line
  `sbom_line_id` bigint NOT NULL COMMENT 'SBOM?ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '????',
  `sbom_header_id` bigint NOT NULL COMMENT 'SBOM?ID',
  `parent_line_id` bigint DEFAULT NULL COMMENT '??ID(???BOM)',
  `line_number` int NOT NULL COMMENT '??',
  `item_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `item_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `item_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: HOST/ACCESSORY/SERVICE/LICENSE/SOFTWARE/PACKAGE',
  `quantity` decimal(12,4) DEFAULT '1.0000' COMMENT '??',
  `unit` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'PCS' COMMENT '??',
  `is_required` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '????(0? 1?)',
  `is_replaceable` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '?????(0? 1?)',
  `replacement_group` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '???',
  `is_phantom` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0? 1?, Phantom Item)',
  `min_qty` decimal(12,4) DEFAULT NULL COMMENT '????',
  `max_qty` decimal(12,4) DEFAULT NULL COMMENT '????',
  `price_impact` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????: FIXED/VARIABLE/NONE',
  `lead_time_days` int DEFAULT NULL COMMENT '??(?)',
  `sort_order` int DEFAULT '0',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`sbom_line_id`),
  UNIQUE KEY `uk_header_line` (`tenant_id`,`sbom_header_id`,`line_number`),
  KEY `idx_header` (`tenant_id`,`sbom_header_id`),
  KEY `idx_parent` (`tenant_id`,`parent_line_id`),
  KEY `idx_type` (`tenant_id`,`item_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??BOM?'

-- cpq_mbom_line
  `mbom_line_id` bigint NOT NULL COMMENT 'MBOM?ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '????',
  `sbom_line_id` bigint NOT NULL COMMENT '??SBOM?ID',
  `model_id` bigint NOT NULL COMMENT '????ID',
  `parent_mbom_line_id` bigint DEFAULT NULL COMMENT '?MBOM?ID(???)',
  `line_number` int NOT NULL COMMENT '??',
  `material_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??????',
  `material_desc` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `material_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????: RAW/SEMI/FINISHED/PACKAGE',
  `quantity` decimal(12,4) NOT NULL COMMENT '??',
  `unit` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'PCS',
  `plant` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????(Plant-Specific BOM)',
  `storage_location` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `requirement_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'M' COMMENT '????: M??/O??',
  `substitute_group` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '???',
  `substitute_priority` int DEFAULT NULL COMMENT '?????',
  `cost_component` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????: MATERIAL/LABOR/OVERHEAD/OUTSOURCE',
  `lead_time_days` int DEFAULT NULL COMMENT '??/????(?)',
  `moq` decimal(12,4) DEFAULT NULL COMMENT '?????',
  `sort_order` int DEFAULT '0',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`mbom_line_id`),
  KEY `idx_sbom` (`tenant_id`,`sbom_line_id`),
  KEY `idx_model` (`tenant_id`,`model_id`),
  KEY `idx_parent` (`tenant_id`,`parent_mbom_line_id`),
  KEY `idx_plant` (`tenant_id`,`plant`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??BOM?'

-- cpq_price_book
  `price_book_id` bigint NOT NULL COMMENT '????ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `book_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `book_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: STANDARD/CHANNEL/PROMOTION/REGION',
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'CNY' COMMENT '??',
  `effective_date` date NOT NULL COMMENT '????',
  `expiry_date` date DEFAULT NULL COMMENT '????',
  `priority` int DEFAULT '0' COMMENT '???(????, ??????????)',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`price_book_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_type` (`tenant_id`,`book_type`,`status`),
  KEY `idx_date` (`tenant_id`,`effective_date`,`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????'

-- cpq_price_book_entry
  `entry_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `price_book_id` bigint NOT NULL COMMENT '????ID(FK?cpq_price_book)',
  `model_id` bigint NOT NULL COMMENT '??ID(FK?cpq_product_model)',
  `item_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????(??, ???????)',
  `region_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `channel_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `list_price` decimal(18,2) NOT NULL COMMENT '???',
  `cost_price` decimal(18,2) DEFAULT NULL COMMENT '???(ABAC??: L0???, L3???)',
  `min_price` decimal(18,2) DEFAULT NULL COMMENT '?????(???????)',
  `effective_date` date NOT NULL COMMENT '????',
  `expiry_date` date DEFAULT NULL COMMENT '????',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `variant_id` bigint DEFAULT NULL COMMENT '??ID(FK?cpq_product_variant, NULL=?????)',
  PRIMARY KEY (`entry_id`),
  KEY `idx_book` (`tenant_id`,`price_book_id`),
  KEY `idx_model` (`tenant_id`,`model_id`),
  KEY `idx_region` (`tenant_id`,`region_code`),
  KEY `idx_channel` (`tenant_id`,`channel_code`),
  KEY `idx_entry_variant` (`tenant_id`,`variant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??????'

-- cpq_price_rule
  `price_rule_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `rule_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `rule_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: DISCOUNT/MARKUP/PROMOTION/CONTRACT',
  `priority` int DEFAULT '0' COMMENT '???(????, ?????????????)',
  `condition_json` json DEFAULT NULL COMMENT '??(JSON): {product_ids, regions, channels, customer_types, date_range, quantity_range, ...}',
  `action_json` json NOT NULL COMMENT '??(JSON): {adjustment_type, adjustment_value, adjustment_unit}',
  `approval_threshold` decimal(18,2) DEFAULT NULL COMMENT '???????/????',
  `effective_date` date NOT NULL COMMENT '????',
  `expiry_date` date DEFAULT NULL COMMENT '????',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`price_rule_id`),
  KEY `idx_tenant_type` (`tenant_id`,`rule_type`,`status`),
  KEY `idx_date` (`tenant_id`,`effective_date`,`expiry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????'

-- cpq_volume_tier
  `tier_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `price_book_entry_id` bigint NOT NULL COMMENT '??????ID(FK?cpq_price_book_entry)',
  `min_quantity` decimal(12,4) NOT NULL COMMENT '????',
  `max_quantity` decimal(12,4) DEFAULT NULL COMMENT '????(NULL=??)',
  `unit_price` decimal(18,2) NOT NULL COMMENT '????',
  `sort_order` int DEFAULT '0' COMMENT '???',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`tier_id`),
  KEY `idx_entry` (`tenant_id`,`price_book_entry_id`),
  KEY `idx_quantity` (`tenant_id`,`price_book_entry_id`,`min_quantity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(100???¥100 / 100-500?¥85 / 500+?¥70)'

-- cpq_channel_price
  `channel_price_id` bigint NOT NULL COMMENT '????ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `channel_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????(FK?cpq_channel)',
  `model_id` bigint NOT NULL COMMENT '??ID(FK?cpq_product_model)',
  `channel_list_price` decimal(18,2) NOT NULL COMMENT '?????',
  `channel_discount_pct` decimal(5,2) DEFAULT NULL COMMENT '?????(%)',
  `effective_date` date NOT NULL COMMENT '????',
  `expiry_date` date DEFAULT NULL COMMENT '????',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `variant_id` bigint DEFAULT NULL COMMENT '??ID(FK?cpq_product_variant, NULL=?????)',
  PRIMARY KEY (`channel_price_id`),
  KEY `idx_channel` (`tenant_id`,`channel_code`),
  KEY `idx_model` (`tenant_id`,`model_id`),
  KEY `idx_date` (`tenant_id`,`effective_date`,`expiry_date`),
  KEY `idx_channel_variant` (`tenant_id`,`variant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(????????)'

-- cpq_quote
  `quote_id` bigint NOT NULL COMMENT '???ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `quote_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '?????(????)',
  `opportunity_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????ID(CRM)',
  `account_id` bigint NOT NULL COMMENT '??ID(FK?cpq_account)',
  `account_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????(??)',
  `quote_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'STANDARD' COMMENT '??: STANDARD/RENEWAL/REVISION/QUICK',
  `currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'CNY' COMMENT '??',
  `subtotal` decimal(18,2) DEFAULT NULL COMMENT '??',
  `discount_total` decimal(18,2) DEFAULT NULL COMMENT '????',
  `tax_total` decimal(18,2) DEFAULT NULL COMMENT '??',
  `grand_total` decimal(18,2) DEFAULT NULL COMMENT '??',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'DRAFT' COMMENT '??: DRAFT/CONFIGURING/VALIDATED/PRICING/APPROVING/APPROVED/SENT/WON/LOST/EXPIRED/REJECTED',
  `valid_until` date DEFAULT NULL COMMENT '????',
  `approval_chain_id` bigint DEFAULT NULL COMMENT '?????ID(FK?cpq_approval_chain)',
  `created_by` bigint DEFAULT NULL COMMENT '???ID',
  `created_by_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '?????(??)',
  `create_by` bigint DEFAULT NULL COMMENT '???',
  `submitted_date` datetime DEFAULT NULL COMMENT '????',
  `won_date` datetime DEFAULT NULL COMMENT '????',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`quote_id`),
  UNIQUE KEY `uk_quote_number` (`tenant_id`,`quote_number`),
  KEY `idx_account` (`tenant_id`,`account_id`),
  KEY `idx_status` (`tenant_id`,`status`,`create_time`),
  KEY `idx_created_by` (`tenant_id`,`created_by`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ???'

-- cpq_quote_line_item
  `line_id` bigint NOT NULL COMMENT '???ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `quote_id` bigint NOT NULL COMMENT '???ID(FK?cpq_quote)',
  `parent_line_id` bigint DEFAULT NULL COMMENT '????ID(????)',
  `line_number` int NOT NULL COMMENT '??',
  `model_id` bigint DEFAULT NULL COMMENT '??ID(FK?cpq_product_model)',
  `sbom_line_id` bigint DEFAULT NULL COMMENT 'SBOM??ID(FK?cpq_sbom_line, ???)',
  `item_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: PRODUCT/ACCESSORY/SERVICE/CUSTOM/SOFTWARE/LICENSE',
  `item_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `item_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `quantity` decimal(12,4) NOT NULL COMMENT '??',
  `unit` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'PCS' COMMENT '??',
  `list_price` decimal(18,2) DEFAULT NULL COMMENT '???',
  `unit_price` decimal(18,2) DEFAULT NULL COMMENT '??(???)',
  `discount_pct` decimal(5,2) DEFAULT NULL COMMENT '?????',
  `discount_amount` decimal(18,2) DEFAULT NULL COMMENT '????',
  `net_price` decimal(18,2) DEFAULT NULL COMMENT '??',
  `line_total` decimal(18,2) DEFAULT NULL COMMENT '???',
  `configuration_json` json DEFAULT NULL COMMENT '???????(JSON)',
  `custom_requirements` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '??????',
  `delivery_days` int DEFAULT NULL COMMENT '????(?)',
  `atp_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'ATP??: AVAILABLE/CONSTRAINED/UNAVAILABLE',
  `sort_order` int DEFAULT '0' COMMENT '???',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`line_id`),
  UNIQUE KEY `uk_quote_line` (`tenant_id`,`quote_id`,`line_number`),
  KEY `idx_quote` (`tenant_id`,`quote_id`),
  KEY `idx_model` (`tenant_id`,`model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ?????'

-- cpq_quote_template
  `template_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `template_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `template_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: PDF/DOCX/STANDARD/CUSTOM',
  `template_content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '????(???/HTML/Markdown)',
  `template_json` json DEFAULT NULL COMMENT '????(JSON): {sections, placeholders, styles, ...}',
  `is_default` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??????',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`template_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_type` (`tenant_id`,`template_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????({{config.*}}??????????, PDF/Word??)'

-- cpq_ecn_change_order
  `change_order_id` bigint NOT NULL COMMENT '???ID',
  `tenant_id` varchar(20) DEFAULT '000000' COMMENT '??ID',
  `ecn_number` varchar(50) NOT NULL COMMENT 'ECN??',
  `title` varchar(200) NOT NULL COMMENT '????',
  `reason` text COMMENT '????',
  `change_type` varchar(30) DEFAULT NULL COMMENT '????: PRODUCT/BOM/PRICE/PROCESS/DOCUMENT',
  `severity` varchar(20) DEFAULT 'NORMAL' COMMENT '????: CRITICAL/MAJOR/NORMAL/MINOR',
  `affected_products` text COMMENT '?????(JSON)',
  `status` varchar(20) DEFAULT 'DRAFT' COMMENT '??: DRAFT/ANALYZING/APPROVED/REJECTED/IMPLEMENTED/CLOSED',
  `originator_id` bigint DEFAULT NULL COMMENT '???ID',
  `originator_name` varchar(100) DEFAULT NULL COMMENT '?????',
  `del_flag` char(1) DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`change_order_id`),
  UNIQUE KEY `uk_ecn_number` (`tenant_id`,`ecn_number`),
  KEY `idx_status` (`tenant_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ECN???'

-- cpq_ecn_change_item
  `item_id` bigint NOT NULL COMMENT '???ID',
  `tenant_id` varchar(20) DEFAULT '000000' COMMENT '??ID',
  `change_order_id` bigint NOT NULL COMMENT '???ID(FK)',
  `entity_type` varchar(30) NOT NULL COMMENT '????: PRODUCT/BOM/PRICE/ATTRIBUTE/DOCUMENT/CONFIG_RULE',
  `entity_id` bigint NOT NULL COMMENT '??ID',
  `entity_name` varchar(200) DEFAULT NULL COMMENT '????',
  `change_description` text COMMENT '????',
  `old_value` text COMMENT '??(JSON)',
  `new_value` text COMMENT '??(JSON)',
  `sort_order` int DEFAULT '0' COMMENT '??',
  `del_flag` char(1) DEFAULT '0',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  KEY `idx_change_order` (`tenant_id`,`change_order_id`),
  KEY `idx_entity` (`tenant_id`,`entity_type`,`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ECN???'

-- cpq_crm_opportunity
  `opportunity_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `opportunity_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `opportunity_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `account_id` bigint NOT NULL COMMENT '????ID(FK?cpq_account)',
  `stage` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'PROSPECTING' COMMENT '????',
  `close_date` date DEFAULT NULL COMMENT '??????',
  `amount` decimal(18,2) DEFAULT NULL COMMENT '????',
  `probability` decimal(5,2) DEFAULT NULL COMMENT '????(%)',
  `opportunity_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `lead_source` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `next_step` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '?????',
  `owner_id` bigint DEFAULT NULL COMMENT '???(??ID)',
  `contact_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '?????',
  `contact_phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `is_closed` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0??? 1???)',
  `closed_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????(?????)',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`opportunity_id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_id`,`opportunity_code`),
  KEY `idx_account` (`tenant_id`,`account_id`),
  KEY `idx_owner` (`tenant_id`,`owner_id`),
  KEY `idx_stage` (`tenant_id`,`stage`),
  KEY `idx_close_date` (`tenant_id`,`close_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??'

-- cpq_crm_contract
  `contract_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `contract_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `contract_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `account_id` bigint NOT NULL COMMENT '????ID(FK?cpq_account)',
  `opportunity_id` bigint DEFAULT NULL COMMENT '????ID(FK?cpq_crm_opportunity)',
  `contract_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'PROJECT' COMMENT '????: PROJECT(????)/FRAMEWORK(????)',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'DRAFT' COMMENT '????',
  `start_date` date DEFAULT NULL COMMENT '??????',
  `end_date` date DEFAULT NULL COMMENT '??????',
  `total_amount` decimal(18,2) DEFAULT NULL COMMENT '?????',
  `signed_date` date DEFAULT NULL COMMENT '????',
  `signing_party` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `payment_terms` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `owner_id` bigint DEFAULT NULL COMMENT '???(??ID)',
  `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`contract_id`),
  UNIQUE KEY `uk_tenant_number` (`tenant_id`,`contract_number`),
  KEY `idx_account` (`tenant_id`,`account_id`),
  KEY `idx_opportunity` (`tenant_id`,`opportunity_id`),
  KEY `idx_status` (`tenant_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??'

-- cpq_crm_order
  `order_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `order_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `order_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `contract_id` bigint NOT NULL COMMENT '????ID(FK?cpq_crm_contract)',
  `account_id` bigint NOT NULL COMMENT '????ID(FK?cpq_account)',
  `quote_id` bigint DEFAULT NULL COMMENT '?????ID(FK?cpq_quote)',
  `order_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????: STANDARD/RUSH/RENEWAL',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'DRAFT' COMMENT '????',
  `order_date` date DEFAULT NULL COMMENT '????',
  `total_amount` decimal(18,2) DEFAULT NULL COMMENT '?????',
  `currency` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'CNY' COMMENT '??',
  `delivery_date` date DEFAULT NULL COMMENT '??????',
  `shipping_address` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `billing_address` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `owner_id` bigint DEFAULT NULL COMMENT '???(??ID)',
  `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `uk_tenant_number` (`tenant_id`,`order_number`),
  KEY `idx_contract` (`tenant_id`,`contract_id`),
  KEY `idx_account` (`tenant_id`,`account_id`),
  KEY `idx_quote` (`tenant_id`,`quote_id`),
  KEY `idx_status` (`tenant_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??'

-- cpq_currency_rate
  `rate_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `from_currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???',
  `to_currency` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `exchange_rate` decimal(18,6) NOT NULL COMMENT '??',
  `effective_date` date NOT NULL COMMENT '????',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`rate_id`),
  KEY `idx_currency` (`tenant_id`,`from_currency`,`to_currency`),
  KEY `idx_date` (`tenant_id`,`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??(???????)'

-- cpq_approval_rule
  `rule_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `rule_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `trigger_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????: DISCOUNT_EXCEED(????)/MARGIN_BELOW(????)/AMOUNT_ABOVE(????)/NEW_CONFIG(????)/CROSS_REGION(???)/CUSTOM_PART(???)/FIRST_ORDER(??)/EXPORT_CONTROL(????)',
  `trigger_value` decimal(18,2) DEFAULT NULL COMMENT '????(???>20%????)',
  `approval_chain_json` json NOT NULL COMMENT '?????(JSON): [{step, approver_role, approver_ids, type:PARALLEL/SERIAL}]',
  `priority` int DEFAULT '0' COMMENT '???(????, ???????????????)',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`rule_id`),
  KEY `idx_trigger` (`tenant_id`,`trigger_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(8?????: ????/????/????/????/???/???/??/????)'

-- cpq_approval_record
  `record_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `chain_id` bigint NOT NULL COMMENT '???ID(FK?cpq_approval_chain)',
  `step_number` int NOT NULL COMMENT '???',
  `approver_id` bigint NOT NULL COMMENT '???ID',
  `approver_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '?????(??)',
  `action` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????: APPROVE/CONDITIONAL_APPROVE/REJECT/TRANSFER(??)/DELEGATE(??)/ADD_SIGNER(??)',
  `comment` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `action_time` datetime DEFAULT NULL COMMENT '????',
  `sla_deadline` datetime DEFAULT NULL COMMENT 'SLA????',
  PRIMARY KEY (`record_id`),
  KEY `idx_chain` (`tenant_id`,`chain_id`),
  KEY `idx_approver` (`tenant_id`,`approver_id`,`action_time`),
  KEY `idx_sla` (`tenant_id`,`sla_deadline`,`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(?????????: ??/????/??/??/??/??)'

-- cpq_system_config
  `config_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `config_key` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???',
  `config_value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???',
  `config_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'STRING' COMMENT '???: STRING/NUMBER/JSON/BOOLEAN',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`config_id`),
  UNIQUE KEY `uk_key` (`tenant_id`,`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(??RuoYi sys_config, ??CPQ???????)'

-- cpq_product_variant
  `variant_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `model_id` bigint NOT NULL COMMENT '??????ID(FK?cpq_product_model)',
  `variant_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????(? RW-SWEEP-S1P-WHT)',
  `variant_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????(? SweepBot S1 Pro ???)',
  `attributes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '?????(JSON): {"attr_name":"attr_value", ...}',
  `default_bom_id` bigint DEFAULT NULL COMMENT '????????SBOM Header ID(FK?cpq_sbom_header)',
  `base_price` decimal(18,2) DEFAULT NULL COMMENT '?????(???model.base_price???)',
  `thumbnail_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '?????',
  `is_default` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??????(0? 1?)',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL COMMENT '????',
  `create_by` bigint DEFAULT NULL COMMENT '???',
  `create_time` datetime DEFAULT NULL COMMENT '????',
  `update_by` bigint DEFAULT NULL COMMENT '???',
  `update_time` datetime DEFAULT NULL COMMENT '????',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??',
  PRIMARY KEY (`variant_id`),
  UNIQUE KEY `uk_variant_code` (`tenant_id`,`variant_code`),
  UNIQUE KEY `uk_model_attrs` (`tenant_id`,`model_id`,`attributes`(255)),
  KEY `idx_model` (`tenant_id`,`model_id`),
  KEY `idx_default` (`tenant_id`,`model_id`,`is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(??+???????????SKU)'

-- cpq_bundle
  `bundle_id` bigint NOT NULL COMMENT '???ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `model_id` bigint NOT NULL COMMENT '?????ID(FK?cpq_product_model, config_type=BUNDLE)',
  `bundle_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: FIXED/CONFIGURABLE/SOLUTION',
  `pricing_strategy` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????: BUNDLE_PRICE/SUM_COMPONENTS',
  `bundle_discount_pct` decimal(5,2) DEFAULT NULL COMMENT '?????(%)',
  `is_active` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '????',
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`bundle_id`),
  KEY `idx_model` (`tenant_id`,`model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ???????'

-- cpq_compatibility_matrix
  `matrix_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `source_product_id` bigint NOT NULL COMMENT '???ID(FK?cpq_product_model)',
  `target_product_id` bigint NOT NULL COMMENT '????ID(FK?cpq_product_model)',
  `compatibility_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????: MUTUAL_EXCLUSIVE(??)/DEPENDENCY(??)/REQUIRES(??)',
  `condition_desc` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??????',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`matrix_id`),
  UNIQUE KEY `uk_product_pair` (`tenant_id`,`source_product_id`,`target_product_id`,`compatibility_type`),
  KEY `idx_source` (`tenant_id`,`source_product_id`),
  KEY `idx_target` (`tenant_id`,`target_product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????????(??A???B??/??/????)'

-- cpq_competitor
  `competitor_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) DEFAULT '000000',
  `competitor_name` varchar(100) NOT NULL COMMENT '????',
  `competitor_code` varchar(64) DEFAULT NULL COMMENT '????',
  `industry` varchar(100) DEFAULT NULL COMMENT '??',
  `website` varchar(200) DEFAULT NULL COMMENT '??',
  `description` text COMMENT '??',
  `market_share` decimal(5,2) DEFAULT NULL COMMENT '????(%)',
  `status` char(1) DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`competitor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='???'

-- cpq_competitor_product
  `product_id` bigint NOT NULL COMMENT '????ID',
  `tenant_id` varchar(20) DEFAULT '000000',
  `competitor_id` bigint NOT NULL COMMENT '??ID',
  `product_name` varchar(200) NOT NULL COMMENT '????',
  `product_code` varchar(64) DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL COMMENT '????',
  `base_price` decimal(18,2) DEFAULT NULL COMMENT '????',
  `specs_json` json DEFAULT NULL COMMENT '????JSON',
  `strengths` text COMMENT '??',
  `weaknesses` text COMMENT '??',
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0' COMMENT '0?? 2??',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  KEY `idx_competitor` (`tenant_id`,`competitor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='????'

-- cpq_plant
  `plant_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) DEFAULT '000000',
  `plant_code` varchar(50) NOT NULL COMMENT '????',
  `plant_name` varchar(100) NOT NULL COMMENT '????',
  `location` varchar(200) DEFAULT NULL COMMENT '??',
  `capacity_per_day` int DEFAULT '0' COMMENT '???',
  `working_days_per_year` int DEFAULT '250' COMMENT '?????',
  `quality_level` varchar(20) DEFAULT 'STANDARD' COMMENT '????',
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0' COMMENT '0?? 2??',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`plant_id`),
  UNIQUE KEY `uk_plant` (`tenant_id`,`plant_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CPQ????'

-- cpq_channel
  `channel_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `channel_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `channel_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `channel_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????: DIRECT/DISTRIBUTOR/RESELLER/SI/AGENT',
  `partner_id` bigint DEFAULT NULL COMMENT '????ID(FK?cpq_account, ??????????)',
  `region` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`channel_id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_id`,`channel_code`),
  KEY `idx_type` (`tenant_id`,`channel_type`),
  KEY `idx_partner` (`tenant_id`,`partner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??'

-- cpq_territory
  `territory_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `territory_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `territory_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `parent_territory_id` bigint DEFAULT NULL COMMENT '???ID(???, ??????????)',
  `region` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????: CN_NORTH/CN_EAST/CN_SOUTH/CN_WEST/CN_CENTER/APAC/EMEA/AMER',
  `manager_id` bigint DEFAULT NULL COMMENT '????(??ID)',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`territory_id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_id`,`territory_code`),
  KEY `idx_parent` (`tenant_id`,`parent_territory_id`),
  KEY `idx_region` (`tenant_id`,`region`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(????: ??????, ?????????????)'

-- cpq_account
  `account_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `account_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `account_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `account_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????: DIRECT/CHANNEL/PARTNER/ENTERPRISE',
  `industry` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??',
  `region` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??',
  `contact_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '???',
  `contact_phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `contact_email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `legal_representative` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????',
  `unified_social_credit_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '????????',
  `address` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??',
  `tax_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '??',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_id`,`account_code`),
  KEY `idx_name` (`tenant_id`,`account_name`),
  KEY `idx_region` (`tenant_id`,`region`),
  KEY `idx_industry` (`tenant_id`,`industry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ??'

-- cpq_recommendation
  `recommendation_id` bigint NOT NULL COMMENT '????ID',
  `tenant_id` varchar(20) DEFAULT '000000',
  `scenario` varchar(200) NOT NULL COMMENT '????',
  `our_product_id` bigint NOT NULL COMMENT '??????ID',
  `competitor_product_id` bigint DEFAULT NULL COMMENT '??????ID',
  `strategy_type` varchar(50) NOT NULL COMMENT '????: PRICE/FEATURE/BUNDLE/SERVICE',
  `strategy_desc` text COMMENT '????',
  `priority` int DEFAULT '0' COMMENT '???',
  `effective_from` date DEFAULT NULL,
  `effective_to` date DEFAULT NULL,
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0' COMMENT '0?? 2??',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`recommendation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='??????'

-- cpq_solution_document
  `document_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `quote_id` bigint DEFAULT NULL COMMENT '?????ID(FK?cpq_quote)',
  `document_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: TECHNICAL_PROPOSAL/BUSINESS_PROPOSAL/DELIVERY_PLAN/IMPLEMENTATION/ACCEPTANCE',
  `document_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `document_content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '????(Tiptap JSON)',
  `document_json` json DEFAULT NULL COMMENT '???????(JSON)',
  `version` int DEFAULT '1' COMMENT '???',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'DRAFT' COMMENT '??: DRAFT/EDITING/REVIEWING/APPROVED/PUBLISHED',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`document_id`),
  KEY `idx_quote` (`tenant_id`,`quote_id`),
  KEY `idx_type` (`tenant_id`,`document_type`),
  KEY `idx_status` (`tenant_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(?????: ?????/?????/????/????)'

-- cpq_knowledge_article
  `article_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) DEFAULT '000000',
  `title` varchar(500) NOT NULL COMMENT '??',
  `content` longtext COMMENT '??',
  `category` varchar(100) DEFAULT NULL COMMENT '??',
  `article_type` varchar(20) NOT NULL COMMENT '??: PRODUCT/SCRIPT/CASE/TRAINING',
  `tags` varchar(500) DEFAULT NULL COMMENT '??',
  `view_count` int DEFAULT '0' COMMENT '????',
  `status` char(1) DEFAULT '0' COMMENT '??(0?? 1??)',
  `del_flag` char(1) DEFAULT '0' COMMENT '????(0?? 2??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`article_id`),
  KEY `idx_type` (`tenant_id`,`article_type`,`status`),
  FULLTEXT KEY `ft_title_content` (`title`,`content`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CPQ?????'

-- cpq_config_snapshot
  `snapshot_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `quote_id` bigint NOT NULL COMMENT '???ID(FK?cpq_quote)',
  `model_id` bigint NOT NULL COMMENT '??ID(FK?cpq_product_model)',
  `snapshot_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????(SHA256)',
  `selections_json` json NOT NULL COMMENT '????(JSON): {attr_name: attr_value, ...}',
  `bom_json` json DEFAULT NULL COMMENT '??BOM??(JSON): {lines: [{item_code, qty, ...}]}',
  `rule_version` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '???????',
  `price_version` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '???????',
  `product_version` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '???????',
  `snapshot_time` datetime NOT NULL COMMENT '????',
  PRIMARY KEY (`snapshot_id`),
  UNIQUE KEY `uk_snapshot_hash` (`tenant_id`,`snapshot_hash`),
  KEY `idx_quote` (`tenant_id`,`quote_id`),
  KEY `idx_model` (`tenant_id`,`model_id`),
  KEY `idx_time` (`tenant_id`,`snapshot_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(????: ??????????+BOM+????, ???????????)'

-- cpq_abac_policy
  `policy_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '????',
  `policy_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????',
  `policy_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????: COST_VISIBILITY/REGION_SCOPE/PRODUCT_LINE_SCOPE',
  `subject_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '????: ROLE/USER/DEPT',
  `subject_value` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???(role_key/user_id/dept_id)',
  `attribute_key` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???: cost_visibility_level/region_list/product_line_list',
  `attribute_value` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '???: 0-3/csv??/csv??',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '??(0?? 1??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '????(0?? 2??)',
  PRIMARY KEY (`policy_id`),
  KEY `idx_tenant` (`tenant_id`),
  KEY `idx_subject` (`tenant_id`,`subject_type`,`subject_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ ABAC???'

-- cpq_sync_log
  `log_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '000000' COMMENT '??ID',
  `config_id` bigint NOT NULL COMMENT '????ID(FK?cpq_integration_config)',
  `sync_direction` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: INBOUND(???CPQ)/OUTBOUND(CPQ???)',
  `sync_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '??: SUCCESS/FAILED/PARTIAL',
  `records_total` int DEFAULT NULL COMMENT '????',
  `records_success` int DEFAULT NULL COMMENT '???',
  `records_failed` int DEFAULT NULL COMMENT '???',
  `error_detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '????',
  `sync_time` datetime NOT NULL COMMENT '????',
  `duration_ms` int DEFAULT NULL COMMENT '??(??)',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '0?? 2??',
  PRIMARY KEY (`log_id`),
  KEY `idx_config_time` (`tenant_id`,`config_id`,`sync_time` DESC),
  KEY `idx_status` (`tenant_id`,`sync_status`,`sync_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='CPQ????(???????????????)'

-- cpq_migration_log
  `log_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) DEFAULT '000000',
  `task_id` bigint NOT NULL COMMENT '????ID',
  `row_index` int DEFAULT NULL COMMENT '??',
  `log_level` varchar(20) DEFAULT 'INFO' COMMENT '??: INFO/WARN/ERROR',
  `message` text COMMENT '????',
  `raw_data_json` json DEFAULT NULL COMMENT '????',
  `log_time` datetime DEFAULT NULL,
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `del_flag` char(1) DEFAULT '0' COMMENT '0?? 2??',
  PRIMARY KEY (`log_id`),
  KEY `idx_task` (`tenant_id`,`task_id`),
  KEY `idx_tenant_del` (`tenant_id`,`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='????'

-- cpq_migration_task
  `task_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) DEFAULT '000000',
  `task_name` varchar(200) NOT NULL COMMENT '????',
  `source_system` varchar(50) NOT NULL COMMENT '???: LEGACY_ERP/CRM/EXCEL',
  `target_module` varchar(50) NOT NULL COMMENT '????: PRODUCT/PRICING/CUSTOMER',
  `task_status` varchar(20) DEFAULT 'DRAFT' COMMENT '??: DRAFT/VALIDATING/RUNNING/COMPLETED/FAILED',
  `total_records` int DEFAULT '0' COMMENT '????',
  `processed_records` int DEFAULT '0' COMMENT '????',
  `failed_records` int DEFAULT '0' COMMENT '???',
  `file_path` varchar(500) DEFAULT NULL COMMENT '??????',
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `del_flag` char(1) DEFAULT '0' COMMENT '0?? 2??',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='??????'

-- cpq_migration_mapping
  `mapping_id` bigint NOT NULL COMMENT '??ID',
  `tenant_id` varchar(20) DEFAULT '000000',
  `task_id` bigint NOT NULL COMMENT '????ID',
  `source_field` varchar(100) NOT NULL COMMENT '???',
  `target_field` varchar(100) NOT NULL COMMENT '????',
  `transform_rule` varchar(500) DEFAULT NULL COMMENT '????',
  `default_value` varchar(200) DEFAULT NULL COMMENT '???',
  `is_required` char(1) DEFAULT '0' COMMENT '????',
  `sort_order` int DEFAULT '0',
  `del_flag` char(1) DEFAULT '0' COMMENT '0?? 2??',
  `create_dept` bigint DEFAULT NULL,
  `create_by` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` bigint DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`mapping_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='??????'

